### ISSUE TITLE
undefined symbol: _gfortran_stop_numeric_f08

### ISSUE THREAD

**Issue by nasica88** [poweraikorea/mldl-powerai#3]
아래 URL의 sample에 따라 python 예제를 수행하는데 아래와 같은 undefined error가 납니다.

https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/

minsky@minsky:~/exam$ python lstm1.py
...
    import scipy.special as spec
  File "/home/minsky/anaconda3/lib/python3.6/site-packages/scipy/special/__init__.py", line 6   40, in <module>
    from ._ufuncs import *
ImportError: /home/minsky/anaconda3/lib/python3.6/site-packages/scipy/special/_ufuncs.cpython   -36m-powerpc64le-linux-gnu.so: undefined symbol: _gfortran_stop_numeric_f08

Redhat 7.4 환경에서 Anaconda 5.1 버전의 python 3.6을 사용하고 있습니다.    전에는 없던 error인데 원인이 무엇인가요 ?

**Comment by nasica88** [comment]
이건 꼭 ppc64le 환경에서만 나는 error는 아닙니다.  그러나 최근에 저도 caffe를 build하면서 이와 유사한 undefined symbol error로 인해 고생을 한 적이 있습니다. 

이 error는 한줄 요약하면 올해 초에 release된 Anaconda 5.1 때문에 발생하는 것입니다.  그렇다고 Anaconda 5.1에 bug가 있는 것은 아니고, Anaconda 5.1을 build하기 위해 사용된 gcc 버전이 7.2.0이라는 것에 문제가 있는 것입니다.

minsky@minsky:~/exam$ python
Python 3.6.4 |Anaconda, Inc.| (default, Feb 11 2018, 08:19:13)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

저  undefined symbol error는 서로 다른 버전의 gcc로 compile된 object file들을 하나로 link할 때 주로 발생합니다.  따라서 Anaconda 5.1 환경에서 gcc로 뭔가 build할 때는 gcc 버전도 7.2로 맞추는 것이 좋습니다.  그러나 Redhat 7.4의 경우 포함된 gcc의 default 버전은 4.8이고, Ubuntu 16.04도 5.4에 불과합니다.

minsky@minsky:~/exam$ gcc --version
gcc (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

다시 말해, Anaconda 5.1에 포함된 python library들은 gcc 7.2로 compile된 것에 비해 OS에 포함된 gcc 버전은 훨씬 낮기 때문에 이 문제가 발생합니다. 

**이 문제를 해결하려면 어떻게 해야 할까요 ?  가장 간단한 방법은 Anaconda 5.0을 쓰는 것입니다.  이 버전은 gcc 4.8로 compile되었거든요.** 

https://repo.continuum.io/archive/

Filename Size Last Modified MD5
Anaconda2-5.1.0-Linux-ppc64le.sh 267.3M 2018-02-15 09:08:49 e894dcc547a1c7d67deb04f6bba7223a
Anaconda3-5.1.0-Linux-ppc64le.sh 285.7M 2018-02-15 09:08:56 47b5b2b17b7dbac0d4d0f0a4653f5b1c
Anaconda2-5.0.0-Linux-ppc64le.sh 282.3M 2017-09-26 16:25:07 157890d591c61a9b511f8452476d6d19
Anaconda3-5.0.0-Linux-ppc64le.sh 296.3M 2017-09-25 14:39:31 8fe5b29ca5be3ff11411621f79babfc2

아래와 같이 Anaconda 5.0을 download 받아 설치하면 그 속에 든 python은 GCC 4.8.4로 build된 것을 보실 수 있습니다.

minsky@minsky:~/files$ wget https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-ppc64le.sh

minsky@minsky:~/exam$ which python
/home/minsky/anaconda3_50/bin/python

minsky@minsky:~/exam$ python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 15 2017, 20:38:23)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

이제 이 환경에서 수행하시면 문제가 사라질 것입니다.

**Comment by poweraikorea** [comment]
이건 꼭 ppc64le 환경에서만 나는 error는 아닙니다. 그러나 최근에 저도 caffe를 build하면서 이와 유사한 undefined symbol error로 인해 고생을 한 적이 있습니다.

이 error는 한줄 요약하면 올해 초에 release된 Anaconda 5.1 때문에 발생하는 것입니다. 그렇다고 Anaconda 5.1에 bug가 있는 것은 아니고, Anaconda 5.1을 build하기 위해 사용된 gcc 버전이 7.2.0이라는 것에 문제가 있는 것입니다.

minsky@minsky:~/exam$ python
Python 3.6.4 |Anaconda, Inc.| (default, Feb 11 2018, 08:19:13)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

저 undefined symbol error는 서로 다른 버전의 gcc로 compile된 object file들을 하나로 link할 때 주로 발생합니다. 따라서 Anaconda 5.1 환경에서 gcc로 뭔가 build할 때는 gcc 버전도 7.2로 맞추는 것이 좋습니다. 그러나 Redhat 7.4의 경우 포함된 gcc의 default 버전은 4.8이고, Ubuntu 16.04도 5.4에 불과합니다.

minsky@minsky:/exam$ gcc --version
gcc (Ubuntu/IBM 5.4.0-6ubuntu116.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

다시 말해, Anaconda 5.1에 포함된 python library들은 gcc 7.2로 compile된 것에 비해 OS에 포함된 gcc 버전은 훨씬 낮기 때문에 이 문제가 발생합니다.

이 문제를 해결하려면 어떻게 해야 할까요 ? 가장 간단한 방법은 Anaconda 5.0을 쓰는 것입니다. 이 버전은 gcc 4.8로 compile되었거든요.

https://repo.continuum.io/archive/

Filename Size Last Modified MD5
Anaconda2-5.1.0-Linux-ppc64le.sh 267.3M 2018-02-15 09:08:49 e894dcc547a1c7d67deb04f6bba7223a
Anaconda3-5.1.0-Linux-ppc64le.sh 285.7M 2018-02-15 09:08:56 47b5b2b17b7dbac0d4d0f0a4653f5b1c
Anaconda2-5.0.0-Linux-ppc64le.sh 282.3M 2017-09-26 16:25:07 157890d591c61a9b511f8452476d6d19
Anaconda3-5.0.0-Linux-ppc64le.sh 296.3M 2017-09-25 14:39:31 8fe5b29ca5be3ff11411621f79babfc2

아래와 같이 Anaconda 5.0을 download 받아 설치하면 그 속에 든 python은 GCC 4.8.4로 build된 것을 보실 수 있습니다.

minsky@minsky:~/files$ wget https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-ppc64le.sh

minsky@minsky:~/exam$ which python
/home/minsky/anaconda3_50/bin/python

minsky@minsky:~/exam$ python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 15 2017, 20:38:23)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

이제 이 환경에서 수행하시면 문제가 사라질 것입니다.

**Comment by nasica88** [comment]
저같은 경우는 anaconda2 v5.2에서 발생하는 아래와 같은 scipy error에 대해, 그냥 OS의 gcc/g++/gfortran 4.8을  version 7.2로 새로 설치한 뒤 scipy를 새로 설치했더니 해결되었습니다.

  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/misc/__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/special/__init__.py", line 627, in <module>
    from ._ufuncs import *
ImportError: /opt/anaconda2/lib/python2.7/site-packages/scipy/special/_ufuncs.so: undefined symbol: _gfortran_stop_numeric_f08

gcc/g++/gfortran 7.2의 설치는 [여기](http://hwengineer.blogspot.com/2018/05/ppc64le-gcc7-cmake3-source-build.html)를 참조하세요.
